spring:
  application:
    name: ravenTest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
  jpa:
    hibernate:
      ddl-auto: create
  springdoc:
    api-docs:
      path: /api-docs
server:
  servlet:
    context-path: /api